name: dart_blog
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dev_dependencies:
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  json_serializable: ^6.6.2
  lints: ^2.0.0
  test: ^1.21.0

dependencies:
  crypt: ^4.3.0
  dotenv: ^4.1.0
  hive: ^2.2.3
  jinja: ^0.4.2
  json_annotation: ^4.8.1
  orm: ^3.3.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
